### ISSUE TITLE
Readable notes

### ISSUE THREAD

**Issue by hliangdev** [rzeng95/SP00KYB00GIE#2]
Scraps of paper / diary entries / medical logs need to be interactable

**Comment by hliangdev** [comment]
Inspiration:
https://www.mcgill.ca/medicalmuseum/files/medicalmuseum/styles/wysiwyg_large/public/images/old_book_thumbnail.jpg?itok=nzRq5_6-

http://upload.wikimedia.org/wikipedia/en/3/36/Bowdoin_Medical_school.jpg

https://norbertmiller.files.wordpress.com/2013/01/katharina-fried-medical-certificate.jpg

http://www.healthvermont.gov/hc/death_certificate/images/dcs/9.jpg

http://www.concordmonitor.com/csp/mediapool/sites/dt.common.streams.StreamServer.cls?STREAMOID=_hrBu5hb8Q51VbXjkSMZtc$daE2N3K4ZzOUsqbU5sYsmFRdt0chBc5_wlQSy1pX2WCsjLu883Ygn4B49Lvm9bPe2QeMKQdVeZmXF$9l$4uCZ8QDXhaHEp3rvzXRJFdy0KqPHLoMevcTLo3h8xh70Y6N_U_CryOsw6FTOdKL_jpQ-&CONTENTTYPE=image/jpeg

**Comment by hliangdev** [comment]
Bumped up the priority because we need this to give the player hints on how to approach our different AIs

**Comment by rzeng95** [comment]
Scrapping this due to time issues
